### ISSUE TITLE
UserToken::expires_in() will reach zero at some point and will not go back up

### ISSUE THREAD

**Issue by Ved-s** [twitch-rs/twitch_oauth2#150]
https://github.com/twitch-rs/twitch_oauth2/blob/5d726e09872214b88812bf2a219bd8c6d1da3482/src/tokens/user_token.rs#L293-L329

It updates `expires_in` when refreshing, but doesn't update the reference point `struct_created: Instant` being used to calculate expiration time.

**Comment by Emilgardis** [comment]
Thank you for the report!
